### ISSUE TITLE
The file posting window doesn't display a texture from the theme

### ISSUE THREAD

**Issue by Kimaul37** [ClearVision/v6#1]
Hello,
I noticed that the file posting window hasn't a texture from the theme displayed when we open it.
The screenshot I took will say more and better things than me.
![Screenshot for ClearVision v6 issue](https://user-images.githubusercontent.com/28737149/61506279-dfdc4000-a9e1-11e9-8dce-ad9b01d31810.jpg)

**Comment by Zerthox** [comment]
Modals aren't fully themed yet, will be fixed in a future update.

**Comment by Zerthox** [comment]
Closed in favor of #2
