### ISSUE TITLE
Mobile Icon always #43b581

### ISSUE THREAD

**Issue by LeafyLuigi** [ClearVision/v6#5]
The mobile indicator is always a green, rather than whatever the online one was changed to.
![image](https://user-images.githubusercontent.com/13402990/64932801-10bae300-d874-11e9-828c-98208cf172d2.png)
I've changed the "success color" as well to the same hex value as the online color and still had the same issue.

Edit: I should note that this only applies to the user list/open DMs list, not DMs where it's shown at the top.

**Comment by Zerthox** [comment]
Ty, I'll look into it.

**Comment by Zerthox** [comment]
Fixed with https://github.com/ClearVision/v6/commit/cc839a2806f455f7d16b25ebeff7c2c81dbeea65.
